#! /usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import argparse
from tornado.web import (
    Application,
    RequestHandler,
    )
from tornado.ioloop import IOLoop


class PingPongHandler(RequestHandler):
    def get(self):
        self.write('pong!!')


def application_factory():
    app = Application([
        (r'/ping', PingPongHandler),
        ])
    return app


def main(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser()
    parser.add_argument('--port', default=8888, type=int)
    args = parser.parse_args(argv)
    app = application_factory()
    app.listen(args.port)
    IOLoop.current().start()

if __name__ == '__main__':
    app = main()
